(watch all)
(load deftemplates.clp)
(load defclasses.clp)
(load test.clp)
(reset)
(defglobal ?*display* = (x-open-display :0))
(defglobal ?*screen* = (default-screen ?*display*))
(defglobal ?*root* = (root-window ?*display* ?*screen*))
(defglobal ?*window* = (x-create-simple-window ?*display* ?*root* 10 10 500 300 1 (black-pixel ?*display* ?*screen*) (white-pixel ?*display* ?*screen*)))
(x-map-window ?*display* ?*window*)
(x-select-input ?*display* ?*window* KeyPressMask ButtonPressMask)
(println "Send event -> " (x-send-event ?*display* ?*window* FALSE (multifield-to-event-mask (create$ KeyPressMask)) (create$ KeyPress ?*window* ?*root* 1 2 3 4 5 6 7 8 9 10)))
(println "Send event -> " (x-send-event ?*display* ?*window* FALSE (multifield-to-event-mask (create$ ButtonPressMask)) (create$ ButtonPress ?*window* ?*root* 1 2 3 4 5 6 7 8 9 10)))
(println "Next event ->" (x-next-event ?*display*))
(println "Next event ->" (x-next-event ?*display*))
(run)
