(defrule always =>
	(bind ?display (x-open-display :0))
	(bind ?screen (default-screen ?display))
	(bind ?window (x-create-simple-window ?display (root-window ?display ?screen) 10 10 500 300 1 (black-pixel ?display ?screen) (white-pixel ?display ?screen)))
	(x-map-window ?display ?window)
	(bind ?cursor (x-create-font-cursor ?display XC_left_ptr))
	(x-define-cursor ?display ?window ?cursor)
	(bind ?gc (x-create-gc ?display ?window 0))
	(x-set-foreground ?display ?gc (black-pixel ?display ?screen))
	(bind ?font (x-load-query-font ?display fixed))
	(x-set-font ?display ?gc ?font)
	(x-draw-arc ?display ?window ?gc 125 75 200 200 0 (* 360 64))
	(x-draw-arc ?display ?window ?gc 250 150 200 200 0 (* 180 64))
	(x-draw-line ?display ?window ?gc 1 2 300 400)
	(x-draw-point ?display ?window ?gc 195 200)
	(x-draw-point ?display ?window ?gc 197 200)
	(x-draw-point ?display ?window ?gc 199 200)
	(x-draw-point ?display ?window ?gc 200 200)
	(x-draw-point ?display ?window ?gc 205 200)
	(x-draw-point ?display ?window ?gc 210 200)
	(x-draw-point ?display ?window ?gc 215 200)
	(x-draw-point ?display ?window ?gc 220 200)
	(x-draw-point ?display ?window ?gc 230 200)
	(x-draw-point ?display ?window ?gc 250 200)
	(x-draw-point ?display ?window ?gc 200 205)
	(x-draw-point ?display ?window ?gc 200 210)
	(x-draw-point ?display ?window ?gc 200 220)
	(x-draw-point ?display ?window ?gc 200 240)
	(x-draw-rectangle ?display ?window ?gc 10 10 200 75)
	(x-draw-string ?display ?window ?gc 40 200 "Hello, world!")
	(x-draw-string ?display ?window ?gc 200 150 "CLIPS Rules!!")
	(x-select-input ?display ?window ExposureMask ButtonPressMask KeyPressMask KeyReleaseMask)
	(println "Pending events now: " (x-pending ?display))
	(print "Next event: ")
       	(bind ?event (x-peek-event ?display))
	;(println (x-lookup-string ?event))
)
(run)
